#!/usr/bin/env bash
# Reset .env to point at the project's default (main / production)
# Lakebase branch, regardless of the current git branch.
#
# Substrate-only: delegates to `lakebase-branch sync-env --branch main`
# (TS) which honors the trunk-alias mapping (git "main"/"master" resolves
# to the Lakebase default leaf, e.g. "production"). Spring tail mirrors
# refresh-token.sh so Java users can `./mvnw spring-boot:run` after
# resetting to main.
#
# Usage: ./scripts/connect-main-branch.sh
set -euo pipefail

WORK_TREE="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$WORK_TREE" ]; then
  echo "connect-main-branch: must run from a git repo." >&2
  exit 1
fi
cd "$WORK_TREE"

# Resolve + run lakebase-branch through ./scripts/lk (single source of truth; lk
# auto-installs a cold cache). This layout has no root node_modules.
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/resolve-scm-bin.sh"
run_scm_bin lakebase-branch sync-env --cwd "$WORK_TREE" --branch main

if [ -f pom.xml ]; then
  set -a
  # shellcheck source=/dev/null
  source .env 2>/dev/null || true
  set +a
  {
    echo "# Auto-generated by connect-main-branch.sh for branch: ${LAKEBASE_BRANCH_ID:-unknown}"
    echo "# No password: the app mints a short-lived Lakebase token at runtime."
    echo "spring.datasource.url=jdbc:postgresql://${LAKEBASE_HOST:-}:5432/${PGDATABASE:-databricks_postgres}?sslmode=require&ApplicationName=${PGAPPNAME:-scm-utils/{{LAKEBASE_SCM_UTILS_VERSION}}}"
    echo "spring.datasource.username=${DB_USERNAME:-}"
  } > application-local.properties
fi

echo "Connected to default Lakebase branch ('${LAKEBASE_BRANCH_ID:-?}'). Updated .env and application-local.properties."
