#!/usr/bin/env bash
# Refresh Lakebase short-lived credentials for the current git branch.
#
# Substrate-only: delegates to `lakebase-branch sync-env` (TS) for the
# .env rewrite + credential mint + git-branch -> Lakebase-leaf mapping.
# Keeps a small Spring tail that writes application-local.properties
# when pom.xml is detected, so Java users do not have to source .env
# into their Maven invocation manually.
#
# Usage:
#   ./scripts/refresh-token.sh                    # refresh only
#   ./scripts/refresh-token.sh ./mvnw spring-boot:run
set -euo pipefail

WORK_TREE="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$WORK_TREE" ]; then
  echo "refresh-token: must run from a git repo." >&2
  exit 1
fi
cd "$WORK_TREE"

# Resolve + run the substrate's lakebase-branch CLI through ./scripts/lk (the
# single source of truth: lk resolves the shared version-keyed cache and
# auto-installs a cold one). This layout has no root node_modules, so a
# node_modules/.bin probe can never be satisfied here.
# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/resolve-scm-bin.sh"
run_scm_bin lakebase-branch sync-env --cwd "$WORK_TREE"

# Spring tail: mirror SPRING_DATASOURCE_* into application-local.properties
# when pom.xml is present. Values are already in .env after sync-env;
# this projection is the only piece TS sync-env does not own (kept here
# as honest templating, not substrate logic).
if [ -f pom.xml ]; then
  set -a
  # shellcheck source=/dev/null
  source .env 2>/dev/null || true
  set +a
  {
    echo "# Auto-generated by refresh-token.sh for branch: ${LAKEBASE_BRANCH_ID:-unknown}"
    echo "# No password: the app mints a short-lived Lakebase token at runtime."
    echo "spring.datasource.url=jdbc:postgresql://${LAKEBASE_HOST:-}:5432/${PGDATABASE:-databricks_postgres}?sslmode=require&ApplicationName=${PGAPPNAME:-scm-utils/{{LAKEBASE_SCM_UTILS_VERSION}}}"
    echo "spring.datasource.username=${DB_USERNAME:-}"
  } > application-local.properties
fi

echo "Lakebase: token refreshed for branch '${LAKEBASE_BRANCH_ID:-?}'."

if [ $# -gt 0 ]; then
  exec "$@"
fi
