// Auto-generated by Lakebase App Dev Kit (FEIP-7094 Phase 1).
//
// Smoke fixture that proves the Playwright wire-up: the config resolves
// BASE_URL, the runner can fetch it, and the response is reachable. This
// is intentionally NOT an [E2E] AC test, it is the wire-up self-check
// the scaffolder leaves behind so a fresh project can run
// `npm run test:e2e` and get a green before any user-facing scenarios
// exist. Delete or replace once your first real [E2E] row is written.

import { test, expect } from "@playwright/test";

test("playwright wire-up reaches the configured BASE_URL", async ({ page, baseURL }) => {
  expect(baseURL, "BASE_URL must be set via env or playwright.config.ts").toBeTruthy();
  const response = await page.goto("/");
  // Accept any non-5xx response: the kit cannot assume the project has an
  // index route, only that the server is reachable. Real [E2E] tests
  // replace this with their own assertions against feature surfaces.
  expect(response, "fetch against BASE_URL returned no response").not.toBeNull();
  expect(response!.status(), `BASE_URL ${baseURL} returned ${response!.status()}`).toBeLessThan(500);
});
