// Auto-generated by Lakebase App Dev Kit (phase 1).
//
// Playwright config for [E2E]-tagged AC rows. Reads BASE_URL from env so
// the same config drives:
//   - local dev (BASE_URL defaults to the in-tree dev server)
//   - paired-branch CI (BASE_URL = the feature branch's deployed app endpoint)
//   - tier rollouts (BASE_URL = the tier endpoint)
//
// Worker count is parallel-safe by default: each worker shares the single
// per-branch Postgres DSN exposed via DATABASE_URL (the kit's .env flow
// keeps that pointed at the right branch). Tests must scope their data
// writes per-test (UUID rows, schema-prefixed names, etc.) so two workers
// don't trample each other.
//
// Browser matrix: Chromium only for v1 (out-of-scope: Firefox /
// WebKit / mobile / device emulation). Add projects[] entries when those
// land.

import { defineConfig, devices } from "@playwright/test";

const baseURL = process.env.BASE_URL ?? "http://localhost:3000";

// skip the local webServer boot when BASE_URL came from env.
// pr.yml's "Resolve CI app endpoint" step exports LAKEBASE_APP_ENDPOINT ->
// BASE_URL for paired-branch runs; in that mode Playwright should hit the
// deployed app directly rather than booting a duplicate local server (which
// would race the remote app's data and double the run time).
const externalBaseUrl = !!process.env.BASE_URL;

export default defineConfig({
  testDir: "./tests/e2e",
  // Run files in parallel; tests within a file run serially. This matches
  // the kit's "one branch, many tests" model: parallelism is between
  // independent specs, not within a single user flow.
  fullyParallel: true,
  // Surface flakes loudly: zero retries locally, one retry in CI to absorb
  // network jitter against a freshly-provisioned paired branch endpoint.
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: process.env.CI ? [["html", { open: "never" }], ["list"]] : "list",
  use: {
    baseURL,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },
  // Local webServer fires ONLY when BASE_URL is not env-set. Adapt the
  // command to your stack:
  //   - Node.js / Express: keep `npm start`
  //   - Python / FastAPI:  `uv run uvicorn server.app:app --port 3000`
  //   - Java / Spring:     `./mvnw -q spring-boot:run`
  // Set `webServer: undefined` (or delete this block) if your project
  // boots its server some other way and Playwright should never start it.
  webServer: externalBaseUrl
    ? undefined
    : {
        command: "npm start",
        url: baseURL,
        reuseExistingServer: !process.env.CI,
        timeout: 120_000,
      },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
